### ISSUE TITLE
build notification 

### ISSUE THREAD

**Issue by nigll** [cosmin/stashy#104]
Can  somebody give me a example of the usage if the build notification ？
I tried  to  call the method like this：(Is there a problem with my implementation ？)
>>> stash.builds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Stash' object has no attribute 'builds' 

I am expecting a replay。

**Comment by flichtenheld** [comment]
Because I just ran into the same problem, here some things I learned:

1. `import stashy` does not currently import stashy.builds apparently because .builds is not imported anywhere.` import stashy.builds` works though.
2. Since builds is nowhere referenced within Stash(), you have to create the Build() object somewhat manually. Here is what is working for me:

```python
import stashy
import stashy.builds

stash = stashy.connect("https://stash.example.net/", user, password)
build = build = stashy.builds.Build("", stash._client, commit_hash)
build.get()
build.set('INPROGRESS', 'test-stash-api-franklichtenheld', 'Test Stash API (franklichtenheld)', 'https://example.com/build_url', 'Just a test entry, please ignore')
```

Hope this helps

**Comment by cosmin** [comment]
@nigll closing for now, please reopen if the suggestion from @flichtenheld does not work for you
